In [3]:
import numpy as np

In [63]:
w = 2000
h = 1000
N = 16
r = float(w) / h
# Screen coordinates: x0, y0, x1, y1.
# fmt:off
S = (
    -1.0,
    1.0 / r + 0.25,
    1.0,
    -1.0 / r + 0.25
)

In [64]:
points = np.linspace(S[1], S[3], N + 1)[::-1]

In [65]:
points

array([-0.25  , -0.1875, -0.125 , -0.0625,  0.    ,  0.0625,  0.125 ,
        0.1875,  0.25  ,  0.3125,  0.375 ,  0.4375,  0.5   ,  0.5625,
        0.625 ,  0.6875,  0.75  ])

In [66]:
p0, p1 = points[0], points[1]

In [67]:
A = np.repeat(np.linspace(p0, p1, h/N), w)
print(A, A.shape)

[-0.25   -0.25   -0.25   ... -0.1875 -0.1875 -0.1875] (124000,)


/usr/local/Cellar/ipython/6.5.0/libexec/vendor/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.
  """Entry point for launching an IPython kernel.


In [68]:
B = np.repeat(np.arange(p0, p1, 1/h), w)
print(B, B.shape)

[-0.25  -0.25  -0.25  ... -0.188 -0.188 -0.188] (126000,)


In [69]:
w*h/N

125000.0

In [125]:
import math
def next_highest_divisor(N, k):
    t = k
    while N % t != 0:
        t += 1
    return t

In [126]:
divmod(1000, 16)

(62, 8)

In [131]:
f = next_highest_divisor(h, N)
f

20

In [132]:
N

16

In [133]:
h//N

62

In [137]:
h/f

50.0

In [135]:
h

1000